const GET_VIDEOGAMES = "GET_VIDEOGAMES";
const GET_VIDEOGAMES_BY_NAME = "GET_VIDEOGAMES_BY_NAME";
const GET_VIDEOGAME_BY_ID = "GET_VIDEOGAME_BY_ID";
const GET_GENRES = "GET_GENRES";
const REQUEST_POST = "REQUEST_POST";
const RECEIVED_POST = "RECEIVED_POST";

export {
  GET_VIDEOGAMES,
  REQUEST_POST,
  RECEIVED_POST,
  GET_VIDEOGAMES_BY_NAME,
  GET_VIDEOGAME_BY_ID,
  GET_GENRES,
};
